---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "root"
mysql_db: "wordpress"
mysql_user: "user"
mysql_password: "user"

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"