##################################################
# DO Community Playbooks: LAMP on Ubuntu 18.04
##################################################
---
- hosts: webServers
  become: true
  tasks:
    - name: "stop the apache service"
      service:
        name: apache2
        state: stopped